name: Bot Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Uses the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        chmod +x *
        ./deploy.sh install

    - name: create env filw
      run: |
        rm .env*
        cat  <<EOF > .env
        GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
        TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_OWNER=zyexro
        GITHUB_REPO=kernel_builder
        GITHUB_WORKFLOW=main.yml
        EOF
      run: |
        ./deploy.sh start
